---
- name: Install webserver
  hosts: all
  become: yes
  
  tasks:
    
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mysql
        - php
        
    - name: Start and Enable httpd
      service:  
        name: httpd
        state: started
        enabled: yes
        
