---
- name: Install webserver
  hosts: all
  become: yes
  
  tasks:
    
    - name: Start and Enable httpd
      service:  
        name: httpd
        state: stopped
        enabled: yes
    
    - name: Install httpd
      yum:
        name: httpd
        state: absent
