---
- name: Install webserver
  hosts: all
  become: yes
  
  tasks:
    
    - name: Install packages
      yum:
        name: {{ items }}
        state: present
      with_item:
        - httpd
        - mysql
        - php5
        
    - name: Start and Enable httpd
      service:  
        name: httpd
        state: started
        enabled: yes
        
