---

- name: Softwareverteilung Windows
  hosts: all
   
  tasks:
    
    - name: Copy install files to remote hosts
      win_copy:
        src: ./npp.msi
        dest: C:\Windows\Temp\npp.msi
        
    - name: install app: notepad
      win_msi:
        path: C:\Windows\Temp\npp.msi
        wait: yes
#        
#    - name: Remove install files on remote hosts
#      win_file:
#        path: C:\Windows\Temp\npp.msi
#        state: absent
